### PR TITLE
Clean and improve CoCa generation moving to HF

### PR DESCRIPTION
**Pull request by gpucce**
This should add repetition penalty, and use HF logits processors.

@vturrisi took a bit longer but this is the PR (not ready yet), if you have feedback please let me know :)

### CODE REVIEW

**Comment by vturrisi** [comment]
@gpucce no worries! Thanks for getting to it :). I took a quick look and for me it looks fine. I'll try to properly check it later today/tomorrow.

**Comment by gpucce** [comment]
@vturrisi should work now, thanks for pointing out.

I removed some args, however `max_output_length` should be the max length the tokenizer has been trained on while `seq_len` the length of the generation output. Making an example since my writing sounds obscure even to me, I can generate `seq_len=200` tokens only looking at the last `max_seq_len=50` ones for every new one I generate.

**Comment by vturrisi** [comment]
Ah, makes sense. I hadn't understand that before. Also, thanks for the fix :) I'll try to check it again and see if I spot anything else.

**Comment by vturrisi** [comment]
@gpucce I'm testing on some data and it seems like the captions in the new version are much worse (in quality) but I'm not sure why. I get random numbers and words in the middle. Using a (modified) version of what is current in the repo produces much better captions. It can be that I'm applying the repetition penalty on the outputs, but I'm not sure.

```
GENERATION_TYPES = {
    "top_k": top_k,
    "top_p": top_p,
    "top_a": top_a,
    "beam_search": "beam_search",
}


def generate(
    self,
    image,
    text=None,
    seq_len=77,
    max_seq_len=77,
    mask_prob=0.0,
    temperature=1.0,
    generation_type="beam_search",
    filter_thres=0.9,
    repetition_penalty=1.1,
    min_p_pow=2.0,
    min_p_ratio=0.02,
    pad_token_id=None,
    eos_token_id=None,
    sot_token_id=None,
    num_beams=6,
    num_beam_groups=3,
    min_seq_len=5,
    stopping_criteria=None,
    fixed_output_length=False,  # the output will have shape min(seq_len, max_output_len)
):
    sot_token_id = 49406 if sot_token_id is None else sot_token_id
    eos_token_id = 49407 if eos_token_id is None else eos_token_id
    pad_token_id = self.pad_id if pad_token_id is None else pad_token_id

    assert (
        generation_type in GENERATION_TYPES
    ), f"generation_type has to be one of {'| ' + ' | '.join(list(GENERATION_TYPES.keys())) + ' |'}."
    filter_logits_fn = GENERATION_TYPES[generation_type]

    if generation_type == "beam_search":
        return self.generate_beamsearch(
            image_inputs=image,
            max_length=seq_len,
            pad_token_id=pad_token_id,
            eos_token_id=eos_token_id,
            sot_token_id=sot_token_id,
            num_beams=num_beams,
            num_beam_groups=num_beam_groups,
            min_seq_len=min_seq_len,
            stopping_criteria=stopping_criteria,
        )

    assert mask_prob < 1, "mask_prob must be smaller than 1."
    assert seq_len > min_seq_len, "seq_len must be larger than min_seq_len"
    device = image.device

    if text is None:
        text = (
            torch.ones((image.shape[0], 1), device=device, dtype=torch.long)
            * sot_token_id
        )

    was_training = self.training
    num_dims = len(text.shape)

    if num_dims == 1:
        text = text[None, :]

    cur_len = text.shape[1]
    self.eval()
    out = text
    image_latent, image_embs = self._encode_image(image)

    repetition_penalty_processor = RepetitionPenaltyLogitsProcessor(
        penalty=repetition_penalty
    )

    while True:
        x = out[:, -max_seq_len:]
        cur_len = min(cur_len, max_seq_len)
        mask = (out[:, -1] == eos_token_id) | (out[:, -1] == pad_token_id)

        logits = self(
            image,
            x,
            image_latent=image_latent,
            image_embs=image_embs,
            embed_cls=False,
        )["logits"][:, -1]
        logits = repetition_penalty_processor(out, logits)

        sample = (
            torch.ones((out.shape[0], 1), device=device, dtype=torch.long)
            * pad_token_id
        )

        if mask.all():
            if not fixed_output_length:
                break
        else:
            logits = logits[~mask, :]

            if cur_len + 1 < min_seq_len:
                logits = logits[:, :-1]  # eos_token_id is the largest

            if filter_logits_fn in {top_k, top_p}:
                filtered_logits = filter_logits_fn(logits, thres=filter_thres)
                probs = F.softmax(filtered_logits / temperature, dim=-1)

            elif filter_logits_fn is top_a:
                filtered_logits = filter_logits_fn(
                    logits, min_p_pow=min_p_pow, min_p_ratio=min_p_ratio
                )
                probs = F.softmax(filtered_logits / temperature, dim=-1)

            if cur_len + 1 == seq_len:
                sample[~mask, :] = (
                    torch.ones((sum(~mask), 1), device=device, dtype=torch.long)
                    * eos_token_id
                )
            else:
                sample[~mask, :] = torch.multinomial(probs, 1)

        out = torch.cat((out, sample), dim=-1)

        cur_len += 1

        if cur_len >= min_seq_len and cur_len >= seq_len:
            break

    if num_dims == 1:
        out = out.squeeze(0)

    self.train(was_training)
    return out
```

**Comment by gpucce** [comment]
> @gpucce I'm testing on some data and it seems like the captions in the new version are much worse (in quality) but I'm not sure why. I get random numbers and words in the middle. Using a (modified) version of what is current in the repo produces much better captions. It can be that I'm applying the repetition penalty on the outputs, but I'm not sure.
> 
> ```
> GENERATION_TYPES = {
>     "top_k": top_k,
>     "top_p": top_p,
>     "top_a": top_a,
>     "beam_search": "beam_search",
> }
> 
> 
> def generate(
>     self,
>     image,
>     text=None,
>     seq_len=77,
>     max_seq_len=77,
>     mask_prob=0.0,
>     temperature=1.0,
>     generation_type="beam_search",
>     filter_thres=0.9,
>     repetition_penalty=1.1,
>     min_p_pow=2.0,
>     min_p_ratio=0.02,
>     pad_token_id=None,
>     eos_token_id=None,
>     sot_token_id=None,
>     num_beams=6,
>     num_beam_groups=3,
>     min_seq_len=5,
>     stopping_criteria=None,
>     fixed_output_length=False,  # the output will have shape min(seq_len, max_output_len)
> ):
>     sot_token_id = 49406 if sot_token_id is None else sot_token_id
>     eos_token_id = 49407 if eos_token_id is None else eos_token_id
>     pad_token_id = self.pad_id if pad_token_id is None else pad_token_id
> 
>     assert (
>         generation_type in GENERATION_TYPES
>     ), f"generation_type has to be one of {'| ' + ' | '.join(list(GENERATION_TYPES.keys())) + ' |'}."
>     filter_logits_fn = GENERATION_TYPES[generation_type]
> 
>     if generation_type == "beam_search":
>         return self.generate_beamsearch(
>             image_inputs=image,
>             max_length=seq_len,
>             pad_token_id=pad_token_id,
>             eos_token_id=eos_token_id,
>             sot_token_id=sot_token_id,
>             num_beams=num_beams,
>             num_beam_groups=num_beam_groups,
>             min_seq_len=min_seq_len,
>             stopping_criteria=stopping_criteria,
>         )
> 
>     assert mask_prob < 1, "mask_prob must be smaller than 1."
>     assert seq_len > min_seq_len, "seq_len must be larger than min_seq_len"
>     device = image.device
> 
>     if text is None:
>         text = (
>             torch.ones((image.shape[0], 1), device=device, dtype=torch.long)
>             * sot_token_id
>         )
> 
>     was_training = self.training
>     num_dims = len(text.shape)
> 
>     if num_dims == 1:
>         text = text[None, :]
> 
>     cur_len = text.shape[1]
>     self.eval()
>     out = text
>     image_latent, image_embs = self._encode_image(image)
> 
>     repetition_penalty_processor = RepetitionPenaltyLogitsProcessor(
>         penalty=repetition_penalty
>     )
> 
>     while True:
>         x = out[:, -max_seq_len:]
>         cur_len = min(cur_len, max_seq_len)
>         mask = (out[:, -1] == eos_token_id) | (out[:, -1] == pad_token_id)
> 
>         logits = self(
>             image,
>             x,
>             image_latent=image_latent,
>             image_embs=image_embs,
>             embed_cls=False,
>         )["logits"][:, -1]
>         logits = repetition_penalty_processor(out, logits)
> 
>         sample = (
>             torch.ones((out.shape[0], 1), device=device, dtype=torch.long)
>             * pad_token_id
>         )
> 
>         if mask.all():
>             if not fixed_output_length:
>                 break
>         else:
>             logits = logits[~mask, :]
> 
>             if cur_len + 1 < min_seq_len:
>                 logits = logits[:, :-1]  # eos_token_id is the largest
> 
>             if filter_logits_fn in {top_k, top_p}:
>                 filtered_logits = filter_logits_fn(logits, thres=filter_thres)
>                 probs = F.softmax(filtered_logits / temperature, dim=-1)
> 
>             elif filter_logits_fn is top_a:
>                 filtered_logits = filter_logits_fn(
>                     logits, min_p_pow=min_p_pow, min_p_ratio=min_p_ratio
>                 )
>                 probs = F.softmax(filtered_logits / temperature, dim=-1)
> 
>             if cur_len + 1 == seq_len:
>                 sample[~mask, :] = (
>                     torch.ones((sum(~mask), 1), device=device, dtype=torch.long)
>                     * eos_token_id
>                 )
>             else:
>                 sample[~mask, :] = torch.multinomial(probs, 1)
> 
>         out = torch.cat((out, sample), dim=-1)
> 
>         cur_len += 1
> 
>         if cur_len >= min_seq_len and cur_len >= seq_len:
>             break
> 
>     if num_dims == 1:
>         out = out.squeeze(0)
> 
>     self.train(was_training)
>     return out
> ```

Hi I am trying it right now and I am not getting too strange things, from the code you post it looks like you are using an older version? Did you mean to revery to that version?

**Comment by vturrisi** [comment]
Yes, it's an older version. I'm checking individual parts now. I'll try to get back to you soon.

**Comment by gpucce** [comment]
> Yes, it's an older version. I'm checking individual parts now. I'll try to get back to you soon.

Strange, which generation type are you using? And which version of the model maybe?

**Comment by vturrisi** [comment]
top_p and ViT14. One question, these two functions should match right?
```
x = torch.randn(5, 10)
print(TopPLogitsWarper(filter_thres)(None, x))
print(top_p(x, thres=filter_thres))
```

**Comment by gpucce** [comment]
> top_p and ViT14. One question, these two functions should match right?
> 
> ```
> x = torch.randn(5, 10)
> print(TopPLogitsWarper(filter_thres)(None, x))
> print(top_p(x, thres=filter_thres))
> ```

Indeed they are equal if you replace one of the `filter_thres` with `1 - filter_thres` because HuggingFace uses `p` to keep those above and the older `top_p` uses it as those below

**Comment by vturrisi** [comment]
@gpucce So there's a miss-match between the new code and the old code, right? As both functions are called like I did in the snippet.

Also, I tried to see how the old version compares with the new one on a single random image from LAION. As top_p produces different results each time, I re-ran the generation process 10 times. The new version produces:

`['<start_of_text>redhead women and dog next to river . pretty woman and pet looking away in the water . <end_of_text>', '<start_of_text>cool hipster photos of girls and dogs by ivan kuznetsov - 9 <end_of_text>', '<start_of_text>woman with dog on riverbank by ocean with palm trees <end_of_text>', '<start_of_text>people and pets : different categories of dog breeds <end_of_text>', '<start_of_text>stunning _ russian _ fashion _ models _ by _ the _ sea <end_of_text>', '<start_of_text>girl with dog in paris outdoor 3 2 0 x 4 8 0 <end_of_text>', '<start_of_text>best dog names for girls with a puppy and their family <end_of_text>', '<start_of_text>owner of a fashion dog with a beautiful girl in the summer <end_of_text>', '<start_of_text>girl and dog dressed in the style of retro <end_of_text>', '<start_of_text>the essential beauty fashion style with dog on pose <end_of_text>']`

While the old one (with an added `RepetitionPenaltyLogitsProcessor`) produces:

`['<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>', '<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>', '<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>', '<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>', '<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>', '<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>', '<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>', '<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>', '<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>', '<start_of_text>woman and dog sitting on a bridge in the city <end_of_text>']`

The new version produces more noisy (but with higher variance) captions, whereas the old version was less random.

I'm attaching the code below:

```
import types
from io import BytesIO

from open_clip.generation_utils import top_a, top_k, top_p
import open_clip
import requests
import torch
import torch.nn.functional as F
from coca_functions import generate
from PIL import Image
from transformers import (
    LogitsProcessorList,
    MaxLengthCriteria,
    MinLengthLogitsProcessor,
    RepetitionPenaltyLogitsProcessor,
    StoppingCriteriaList,
    TopKLogitsWarper,
    TopPLogitsWarper,
)

coca_model, train_transform, val_transform = open_clip.create_model_and_transforms(
    "coca_ViT-L-14",
    pretrained="laion2B-s13B-b90k",
)
coca_model.eval()

response = requests.get(
    "https://cdn.humoraf.ru/wp-content/uploads/2018/06/sobaki-foto-krasivye-i-smeshnye-106.jpg"
)
img = Image.open(BytesIO(response.content))
img = train_transform(img).unsqueeze(0)


GENERATION_TYPES = {
    "top_k": TopKLogitsWarper,
    "top_p": TopPLogitsWarper,
    "beam_search": "beam_search",
}


def generate1(
    self,
    image,
    text=None,
    seq_len=30,
    max_seq_len=77,
    temperature=1.0,
    generation_type="beam_search",
    filter_thres=0.9,
    pad_token_id=None,
    eos_token_id=None,
    sot_token_id=None,
    num_beams=6,
    num_beam_groups=3,
    min_seq_len=5,
    stopping_criteria=None,
    repetition_penalty=1.0,
    fixed_output_length=False,  # if True output.shape == (batch_size, seq_len)
):
    with torch.no_grad():
        sot_token_id = 49406 if sot_token_id is None else sot_token_id
        eos_token_id = 49407 if eos_token_id is None else eos_token_id
        pad_token_id = self.pad_id if pad_token_id is None else pad_token_id
        logit_processor = LogitsProcessorList(
            [
                MinLengthLogitsProcessor(min_seq_len, eos_token_id),
                RepetitionPenaltyLogitsProcessor(repetition_penalty),
            ]
        )

        if stopping_criteria is None:
            stopping_criteria = [MaxLengthCriteria(max_length=seq_len)]

        stopping_criteria = StoppingCriteriaList(stopping_criteria)

        assert (
            generation_type in GENERATION_TYPES
        ), f"generation_type has to be one of {'| ' + ' | '.join(list(GENERATION_TYPES.keys())) + ' |'}."

        if generation_type == "beam_search":
            return self._generate_beamsearch(
                image_inputs=image,
                pad_token_id=pad_token_id,
                eos_token_id=eos_token_id,
                sot_token_id=sot_token_id,
                num_beams=num_beams,
                num_beam_groups=num_beam_groups,
                min_seq_len=min_seq_len,
                stopping_criteria=stopping_criteria,
                logit_processor=logit_processor,
            )

        assert seq_len > min_seq_len, "seq_len must be larger than min_seq_len"
        device = image.device
        image_latent, image_embs = self._encode_image(image)

        if text is None:
            text = (
                torch.ones((image.shape[0], 1), device=device, dtype=torch.long)
                * sot_token_id
            )

        was_training = self.training
        num_dims = len(text.shape)

        if num_dims == 1:
            text = text[None, :]

        cur_len = text.shape[1]
        self.eval()
        out = text

        logit_warper = GENERATION_TYPES[generation_type](filter_thres)

        while True:
            x = out[:, -max_seq_len:]
            cur_len = x.shape[1]
            logits = self(
                image,
                x,
                image_latent=image_latent,
                image_embs=image_embs,
                embed_cls=False,
            )["logits"][:, -1]
            mask = (out[:, -1] == eos_token_id) | (out[:, -1] == pad_token_id)
            sample = (
                torch.ones((out.shape[0], 1), device=device, dtype=torch.long)
                * pad_token_id
            )

            if mask.all():
                if not fixed_output_length:
                    break
            else:
                logits = logits[~mask, :]
                filtered_logits = logit_processor(x[~mask, :], logits)
                filtered_logits = logit_warper(x[~mask, :], filtered_logits)
                probs = F.softmax(filtered_logits / temperature, dim=-1)

                if cur_len + 1 == seq_len:
                    sample[~mask, :] = (
                        torch.ones((sum(~mask), 1), device=device, dtype=torch.long)
                        * eos_token_id
                    )
                else:
                    sample[~mask, :] = torch.multinomial(probs, 1)

            out = torch.cat((out, sample), dim=-1)

            cur_len += 1

            if stopping_criteria(out, None):
                break

        if num_dims == 1:
            out = out.squeeze(0)

        self.train(was_training)
        return out


kwargs = {
    "min_seq_len": 10,
    "seq_len": 20,
    "repetition_penalty": 1.1,
    "generation_type": "top_p",
}

coca_model.generate = types.MethodType(generate1, coca_model)
print([open_clip.decode(coca_model.generate(img, **kwargs)[0]) for i in range(10)])


GENERATION_TYPES = {
    "top_k": top_k,
    "top_p": top_p,
    "top_a": top_a,
    "beam_search": "beam_search",
}


def generate2(
    self,
    image,
    text=None,
    seq_len=77,
    max_seq_len=77,
    mask_prob=0.0,
    temperature=1.0,
    generation_type="beam_search",
    filter_thres=0.9,
    repetition_penalty=1.1,
    min_p_pow=2.0,
    min_p_ratio=0.02,
    pad_token_id=None,
    eos_token_id=None,
    sot_token_id=None,
    num_beams=6,
    num_beam_groups=3,
    min_seq_len=5,
    stopping_criteria=None,
    fixed_output_length=False,  # the output will have shape min(seq_len, max_output_len)
):
    sot_token_id = 49406 if sot_token_id is None else sot_token_id
    eos_token_id = 49407 if eos_token_id is None else eos_token_id
    pad_token_id = self.pad_id if pad_token_id is None else pad_token_id

    assert (
        generation_type in GENERATION_TYPES
    ), f"generation_type has to be one of {'| ' + ' | '.join(list(GENERATION_TYPES.keys())) + ' |'}."
    filter_logits_fn = GENERATION_TYPES[generation_type]

    if generation_type == "beam_search":
        return self.generate_beamsearch(
            image_inputs=image,
            max_length=seq_len,
            pad_token_id=pad_token_id,
            eos_token_id=eos_token_id,
            sot_token_id=sot_token_id,
            num_beams=num_beams,
            num_beam_groups=num_beam_groups,
            min_seq_len=min_seq_len,
            stopping_criteria=stopping_criteria,
        )

    assert mask_prob < 1, "mask_prob must be smaller than 1."
    assert seq_len > min_seq_len, "seq_len must be larger than min_seq_len"
    device = image.device

    if text is None:
        text = (
            torch.ones((image.shape[0], 1), device=device, dtype=torch.long)
            * sot_token_id
        )

    was_training = self.training
    num_dims = len(text.shape)

    if num_dims == 1:
        text = text[None, :]

    cur_len = text.shape[1]
    self.eval()
    out = text
    image_latent, image_embs = self._encode_image(image)

    repetition_penalty_processor = RepetitionPenaltyLogitsProcessor(
        penalty=repetition_penalty
    )
    while True:
        x = out[:, -max_seq_len:]
        cur_len = min(cur_len, max_seq_len)

        logits = self(
            image, x, image_latent=image_latent, image_embs=image_embs, embed_cls=False
        )["logits"][:, -1]
        logits = repetition_penalty_processor(out, logits)
        mask = (out[:, -1] == eos_token_id) | (out[:, -1] == pad_token_id)
        sample = (
            torch.ones((out.shape[0], 1), device=device, dtype=torch.long)
            * pad_token_id
        )

        if mask.all():
            if not fixed_output_length:
                break
        else:
            logits = logits[~mask, :]

            if cur_len + 1 < min_seq_len:
                logits = logits[:, :-1]  # eos_token_id is the largest

            if filter_logits_fn in {top_k, top_p}:
                filtered_logits = filter_logits_fn(logits, thres=filter_thres)
                probs = F.softmax(filtered_logits / temperature, dim=-1)

            elif filter_logits_fn is top_a:
                filtered_logits = filter_logits_fn(
                    logits, min_p_pow=min_p_pow, min_p_ratio=min_p_ratio
                )
                probs = F.softmax(filtered_logits / temperature, dim=-1)

            if cur_len + 1 == seq_len:
                sample[~mask, :] = (
                    torch.ones((sum(~mask), 1), device=device, dtype=torch.long)
                    * eos_token_id
                )
            else:
                sample[~mask, :] = torch.multinomial(probs, 1)

        out = torch.cat((out, sample), dim=-1)

        cur_len += 1

        if cur_len >= min_seq_len and cur_len >= seq_len:
            break

    if num_dims == 1:
        out = out.squeeze(0)

    self.train(was_training)
    return out


coca_model.generate = types.MethodType(generate2, coca_model)
print([open_clip.decode(coca_model.generate(img, **kwargs)[0]) for i in range(10)])

```

**Comment by vturrisi** [comment]
@gpucce Just tested the latest push, lgtm :) Thanks for the fix!

**Pull request merged**
