### PR TITLE
Introduce norm_gradient_clip parameter.

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by Zasder3** [comment]
LGTM!

**Comment by rom1504** [comment]
Fyi for future readers, this does not seem to help much for stability here.

**Comment by ShilpaGopal** [comment]
@rom1504 Could you describe the rationale behind adding it?

**Comment by rom1504** [comment]
we had hoped this would solve stability issues encountered during large model training (see https://laion.ai/blog/large-openclip/)
it did not help

the only thing we found to help stability issues is bfloat16 (and sometimes reducing learning rate)

**Pull request merged**
