### PR TITLE
remove version limit for protobuf

### LINKED ISSUE #623: Version limit for protobuf
Hi.

Is there a reason for having an upper limit on the `protobuf` package version? (protobuf<4)
I'm using poetry and this forces me to downgrade the `protobuf` version.

### PR DESCRIPTION
**Pull request by SeyedAlirezaFatemi**
Remove the version limit for protobuf since it's no longer needed. The version limit was added because of this issue #246 but that has been resolved in the transformers library with [this](https://github.com/huggingface/transformers/pull/24599) pull request and [commit](https://github.com/huggingface/transformers/commit/299aafe55ff03c565c059682c6fd312e4b89bc2f).

Fixes #623

### CODE REVIEW

**Comment by SeyedAlirezaFatemi** [comment]
I think the tests are failing because of the the new change in [PyTorch 2.1](https://github.com/pytorch/pytorch/releases/tag/v2.1.0)
"Disallow non-bool masks in torch.masked_{select, scatter, fill}"

**Comment by SeyedAlirezaFatemi** [comment]
Tests should get fixed by #665

**Comment by SeyedAlirezaFatemi** [comment]
Wondering how I can retrigger the CI😁🤔

**Comment by SeyedAlirezaFatemi** [comment]
@gabrielilharco Good to merge?😁

**Comment by gabrielilharco** [comment]
tested with `protobuf==4.24.4` and all models and tokenizers load without errors

**Comment by bryant1410** [comment]
Do we need to specify protobuf as a dependency? It's not imported anywhere within this codebase.

**Pull request merged**
