### PR TITLE
Add torch flop counter to profiler

### PR DESCRIPTION
**Pull request by gabrielilharco**

### CODE REVIEW

**Comment by rwightman** [comment]
@gabrielilharco with this, might be worth putting fvcore import in a try/catch so it'll run natively with torch if fvcore isn't installed (minus act count), and then assert if fvcore profile is selected and fvcore module not installed?

**Comment by gabrielilharco** [comment]
Good call, will update

**Comment by gabrielilharco** [comment]
Removing hierarchical flop counting for now until https://github.com/pytorch/pytorch/issues/111809 is resolved. With https://github.com/mlfoundations/open_clip/pull/699 it now works for all supported models

**Comment by rwightman** [comment]
@gabrielilharco looks good, do you want to merge #693 #699 #701 to main and release?

**Comment by gabrielilharco** [comment]
Sounds good!

**Pull request merged**
