### PR TITLE
SigLIP impl

### PR DESCRIPTION
**Pull request by rwightman**
Re #618

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
Can't comment on the distributed part of the code as I don't know that part of PyTorch, but the rest (loss details, bias/temp/inits) LGTM.

**Comment by rwightman** [comment]
@lucasb-eyer thanks for taking a look, yeah the dist part is where a lot of the risk is, but seems to be behaving on local cc12m runs comparing single to 4x GPU.

**Comment by lucasb-eyer** [comment]
FYI: in our code, Basil implemented a small unit-test checking both formulations for "almost equalness" of chunked vs non-chunked, this gave us good reassurance in the implementation (+looking at profiler for memory use).

**Comment by rwightman** [comment]
I've tested
* `convnext_tiny` on cc12m old InfoNCE run vs new SigLIP (36.13 vs 36.46 zero-shot in1k)
* initial convergence w/ siglip + grad accum enabled
* initial convergence of custom text and original clip models w/o siglip (original CLIP InfoNCE loss)
* initial convergence with bidirection exchange and unidirectional
* validating several existing models

Will merge shortly to prevent this getting stale

**Pull request merged**
