### PR TITLE
4 stability changes from lucidrains

### PR DESCRIPTION
**Pull request by rom1504**
testing for now

if positive, I will make sure it's all behind flags + exposed as a configuration

### CODE REVIEW

**Comment by rom1504** [comment]
@lucidrains I merged your 3 changes in one branch, can you please validate if it looks good ?

**Comment by lucidrains** [comment]
yup, looks good 👍

**Comment by rom1504** [comment]
to resume with this:
put strict=False there https://github.com/mlfoundations/open_clip/blob/main/src/training/main.py#L199

and comment out the optimizer load

**Comment by rom1504** [comment]
We didn't end up needing this
Closing for now

**Pull request closed without merging**
