### PR TITLE
Release 2.23.0

### LINKED ISSUE #678: MetaCLIP models release in stable version
Hey, I see that the metaclip models are added in the repository, but the stable version 2.22.0 does not have them incorporated, do you have a planned stable release with them?

### PR DESCRIPTION
**Pull request by gabrielilharco**
Closes #678

### CODE REVIEW

**Comment by rwightman** [comment]
@gabrielilharco FYI I don't think merging release via PR triggers a release @rom1504 ... at least it didn't last time. Also, might want to wait until the nltk thing is fixed up as this will push it into an active release...

**Comment by gabrielilharco** [comment]
@rwightman sgtm, we can wait for the nice SigLIP+CLIPA PR and do a big one. As for the trigger, maybe it depends on how the PR is merged? Seems to work for Squash and merge at least (e.g. https://github.com/mlfoundations/open_clip/pull/511)

**Comment by rom1504** [comment]
It does trigger a release as long as the commit is named "Release X.Y.Z"

**Comment by rom1504** [comment]
What about merging the ntlk thing before the big clippa/siglip is merged? It would not hurt to have some people use the current state of the repo, just in case anything is wrong

**Comment by rwightman** [comment]
@rom1504 it'd be entirely separate fix that I'd have to ignore on the SigLIP PR on merge as I refactored the tokenizers to get rid of the singleton. Someone else is welcome to do that.

**Comment by rom1504** [comment]
Ok if it's not trivial then I guess let's wait

**Pull request merged**
