### PR TITLE
add EVA-CLIP & deepspeed

### PR DESCRIPTION
**Pull request by Quan-Sun**
Signed-off-by: quansun <sunquan@baai.ac.cn>
Add training code of the 1.1B EVA-CLIP(https://arxiv.org/abs/2211.07636)

### CODE REVIEW

**Comment by rom1504** [comment]
new features I see here:
* deepspeed support
* eva vit model
* load visual and text tower independently
* report text and image loss separately
* layer decay with value depending on layer
* support for different lr for text and image

lot of good features!

However, I think it would be much better to split this PR in smaller ones, in order to control better the changes, and help reviewing

**Comment by Quan-Sun** [comment]
> new features I see here:
> 
> * deepspeed support
> * eva vit model
> * load visual and text tower independently
> * report text and image loss separately
> * layer decay with value depending on layer
> * support for different lr for text and image
> 
> lot of good features!
> 
> However, I think it would be much better to split this PR in smaller ones, in order to control better the changes, and help reviewing

Thanks for those suggestions. It's a good idea to split up into smaller PRs. I'll work on this ASAP.

**Comment by nahidalam** [comment]
@Quan-Sun Is this `load visual and text tower independently` feature merged yet?

**Comment by Quan-Sun** [comment]
@nahidalam It's not merged. Maybe you can check https://github.com/baaivision/EVA/tree/master/EVA-CLIP which supports loading visual and text tower independently.

**Pull request closed without merging**
