### PR TITLE
Make clip always output dict in open_clip traininig

### PR DESCRIPTION
**Pull request by gpucce**
This should make clip always use the output dict option when the training is done inside open_clip. 

Partially addressing #390 and fixing #395 

@rwightman

### CODE REVIEW

**Comment by rwightman** [comment]
@gpucce thanks, rather than is running in openclip,  I think it should be `output_dict: Optional[bool] = None` ... if it's default of None, no change is made to the model default, otherwise, it will check attribute and pass through

open_clip will set to True

**Comment by rohan1561** [comment]
Hey, should the forward in the line 263 of training/train.py contain the output_dict argument? It throws an error for now..

**Comment by rwightman** [comment]
@rohan1561 there should be no output dict args in model fwd, don't know why that's still there, guess we missed one @gpucce

**Comment by gpucce** [comment]
Hi, indeed there should not be, I will make a PR with also a test

**Comment by rwightman** [comment]
@gpucce I already pushed  a quick fix, but PR for a test to cover this case would be good

**Pull request merged**
