### PR TITLE
Add colab, example in readme and architecture diagram

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
* readme https://github.com/rom1504/open_clip/tree/readme_colab_diagram
* notebook https://github.com/rom1504/open_clip/blob/readme_colab_diagram/Interacting_with_open_clip.ipynb

**Comment by rom1504** [comment]
@rwightman

**Comment by rwightman** [comment]
@rom1504 CLIP.png and notebook should be moved from root of repo to docs/ folder with other diagrams and documentation related content

Since we're using the README for pypi description, we should use `https://raw.githubusercontent.com/mlfoundations/open_clip/main/docs/CLIP.png` for the CLIP diagram as relative github paths won't work on pypi.

**Comment by rwightman** [comment]
Notebook will be a great example to have, thanks!

**Comment by rom1504** [comment]
Ok sounds good, will fix tomorrow!

**Comment by rom1504** [comment]
@rwightman ok, I just moved the files
is everything else ok?

**Comment by rwightman** [comment]
@rom1504 tx!

**Pull request merged**
