### PR TITLE
Change the last token to eot_token truncating

### PR DESCRIPTION
**Pull request by liyz15**
A fix for https://github.com/mlfoundations/open_clip/issues/130

### CODE REVIEW

**Comment by rom1504** [comment]
Could you do a few inferences with the pretrained models and check if that
makes big changes ?

Ideally running the zero shot on imagenet would be great

**Comment by liyz15** [comment]
Sure! Though I don't expect to see any difference, since all prompt are shorter than 77 tokens

**Comment by liyz15** [comment]
I ran zero-shot on ImageNet with laion400m_e32. As expected, the modification leads little impact with an accuracy 62.92 v.s. 62.94, although in theory nothing is changed at all.

To show the difference, I changed the imagenet templates by randomly choosing 30 template and concating them together as one long template (which is longer than 77 tokens), like this
```python
random.seed(0)
random_selected_template = random.sample(openai_imagenet_template_, 30)
openai_imagenet_template = [
    lambda c: ' or '.join(template(c)[:-1] for template in random_selected_template)
]
```
With this PR, I got an accuracy of 57.49. With the original implementation I got random guess 0.001 which is expected because the sot_token becomes the largest and is used as cls_token, which sees nothing in the text.

**Comment by Zasder3** [comment]
LGTM, thank you for running these tests!

**Pull request merged**
