### PR TITLE
update protobuf minor version

### PR DESCRIPTION
**Pull request by mldangelo**
This allows protobuf to be any version < 4.  This should help users of poetry that require both tensorflow 2.11 and open-clip-torch.

### CODE REVIEW

**Comment by rwightman** [comment]
@lopho @rom1504 re #246 ... what's the max version of protobuf we can support?  will < 4 cause any issues with mt5? I think I'd rather break one model (ie people that wan't mt5 have to install a more restrictive protobuf) than break for everyone that needs other libs in their env.. hmm

**Comment by dsully** [comment]
+1 to this change. I'm seeing this right now due to the (effective) pin:
```
Unable to find a resolution for protobuf
because of the following conflicts:
  protobuf<3.20,>=3.9.2 (from tensorflow@2.11.0)
  protobuf<4,>=3.9.2 (from tensorboard@2.11.0)
  protobuf==3.20.* (from open-clip-torch@2.14.0)
```

**Comment by rwightman** [comment]
so 3.9.2 would be need for both tf and tb to work, so I guess the q is does sentencepiece work with that, we'll have to break one or the other if there isn't a common version for all cases ... the joys of protobuf :/

**Comment by rwightman** [comment]
Since we dont have any petrained weights for mt5, going to merge and deal with any issues related to sentencepiece later, it should be an optional import and not a req dep anyways if there are no weights yet...

**Pull request merged**
