### PR TITLE
wrapped patchdropout in a torch.nn.Module

### LINKED ISSUE #292: PatchDropout breaks JIT
JIT is not working because PatchDropout is not a pytorch module. Error trace when loading a model through `clip-retrieval`:
```
Traceback (most recent call last):
  File "/home/mambaforge/envs/diffusion/bin/clip-retrieval", line 33, in <module>
    sys.exit(load_entry_point('clip-retrieval', 'console_scripts', 'clip-retrieval')())
  File "/home/code/clip-retrieval/clip_retrieval/cli.py", line 18, in main
    fire.Fire(
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/code/clip-retrieval/clip_retrieval/clip_back.py", line 965, in clip_back
    clip_resources = load_clip_indices(
  File "/home/code/clip-retrieval/clip_retrieval/clip_back.py", line 938, in load_clip_indices
    clip_resources[name] = load_clip_index(clip_options)
  File "/home/code/clip-retrieval/clip_retrieval/clip_back.py", line 860, in load_clip_index
    model, preprocess = load_clip(clip_options.clip_model, use_jit=clip_options.use_jit, device=device)
  File "/home/code/clip-retrieval/clip_retrieval/load_clip.py", line 73, in load_clip
    model, preprocess = load_clip_without_warmup(clip_model, use_jit, device, clip_cache_path)
  File "/home/code/clip-retrieval/clip_retrieval/load_clip.py", line 62, in load_clip_without_warmup
    model, preprocess = load_open_clip(clip_model, use_jit, device, clip_cache_path)
  File "/home/code/clip-retrieval/clip_retrieval/load_clip.py", line 49, in load_open_clip
    model, _, preprocess = open_clip.create_model_and_transforms(
  File "/home/code/open_clip/src/open_clip/factory.py", line 207, in create_model_and_transforms
    model = create_model(
  File "/home/code/open_clip/src/open_clip/factory.py", line 187, in create_model
    model = torch.jit.script(model)
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/torch/jit/_script.py", line 1286, in script
    return torch.jit._recursive.create_script_module(
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/torch/jit/_recursive.py", line 480, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/torch/jit/_recursive.py", line 542, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/torch/jit/_script.py", line 615, in _construct
    init_fn(script_module)
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/torch/jit/_recursive.py", line 520, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/torch/jit/_recursive.py", line 546, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/mambaforge/envs/diffusion/lib/python3.10/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Module 'VisionTransformer' has no attribute 'patch_dropout' (This attribute exists on the Python module, but we failed to convert Python type: 'open_clip.transformer.PatchDropout' to a TorchScript type. Only tensors and (possibly nested) tuples of tensors, lists, or dictsare supported as inputs or outputs of traced functions, but instead got value of type PatchDropout.. Its type was inferred; try adding a type annotation for the attribute.):
  File "/home/code/open_clip/src/open_clip/transformer.py", line 383
    
        # a patch_dropout of 0. would mean it is disabled and this function would do nothing but return what was passed in
        x = self.patch_dropout(x, self.training)
            ~~~~~~~~~~~~~~~~~~ <--- HERE
        x = self.ln_pre(x)

```

### PR DESCRIPTION
**Pull request by taiqihe**
Fixes #292

### CODE REVIEW

**Comment by lucidrains** [comment]
@taiqihe will you run into errors trying to load older models? the reason i didn't modularize it is so that it is backwards compatible

**Comment by rwightman** [comment]
I agree it should be a module, to make it backwards compatible, lets not instantiate it unless it's being used.

`self.patch_dropout = PatchDropout(patch_dropout) if patch_dropout else nn.Identity()`

**Comment by rwightman** [comment]
But it doesn't have any parameters so don't think that's a concern anyways, I feel for a repo like this, the only valid worry re backwards compatibility are changes that 
* have a significant chance of  altering runtime performance (this is essentially no op if the if returns)
* add/remove parameters and thus break loading of old checkpoints (this layer even if present does not add new params or permanent buffers)
* change numerics / ops such that results are different (again, no-op if not used)

I don't feel that worrying about full model pickle, etc is valid compatibility, that should never be done in the first place.

**Comment by lucidrains** [comment]
> I agree it should be a module, to make it backwards compatible, lets not instantiate it unless it's being used.
> 
> `self.patch_dropout = PatchDropout(patch_dropout) if patch_dropout else nn.Identity()`

yup, this is good! 💯

**Comment by taiqihe** [comment]
I updated the initialization with the latest commit

**Comment by rom1504** [comment]
is this good now ? I'd like to make a release so dependent packages are not broken anymore

**Comment by rom1504** [comment]
well it looks fine to me

**Pull request merged**
